spring:
#  cloud:
#    gateway:
#      routes:
#        - id: servlet-app
#          uri: http://localhost:8090
#          predicates:
#            - Path=/, /profile
#          filters:
#            - TokenRelay=
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 261397464923860
            client-secret: <secret id>
#logging:
#  level:
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE
#        http:
#          server:
#            reactive: TRACE
#        web:
#          reactive: TRACE
#        boot:
#          autoconfigure:
#            web: TRACE
#    reactor:
#      netty: TRACE