spring:
  profiles:
    active: @spring.profiles.active@
management:
  health:
    probes:
      enabled: true
#  endpoint.health.group:
#    liveness.include: livenessProbe
#    readness.include: readnessProbe